In [5]:
pip install tensorflow

In [48]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.19.0


In [7]:
#Create a scalar (0-D tensor)
a=tf.constant(5)
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [8]:
#Create a vector (1-D tensor)
v = tf.constant([1, 2, 3, 4])
print(v)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [9]:
# Create a matrix (2-D tensor)
m = tf.constant([[1, 2],
                 [3, 4]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
#Create a 3-D tensor
n=tf.constant([[1,2],[3,4],[5,6]])
print(n)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [12]:
#Specify data type explicitly
x = tf.constant([1, 2, 3], dtype=tf.float32)
print(x)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [14]:

z = tf.zeros((2, 3))
print(z)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [15]:
o = tf.ones((3, 2))
print(o)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [16]:
r = tf.range(1, 10, 2)
print(r)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [20]:
rn = tf.random.normal((2, 2))
print(rn)

tf.Tensor(
[[-1.0953372   1.3889338 ]
 [-1.4933401   0.12310013]], shape=(2, 2), dtype=float32)


In [18]:
ru = tf.random.uniform((2, 2), minval=0, maxval=10)
print(ru)

tf.Tensor(
[[2.8134441 3.8843918]
 [9.781914  8.681083 ]], shape=(2, 2), dtype=float32)


In [22]:
#Convert to NumPy
print(v.numpy())

[1 2 3 4]


In [23]:
print("Shape:", m.shape)
print("Dtype:", m.dtype)
print("Rank:", tf.rank(m))

Shape: (2, 2)
Dtype: <dtype: 'int32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)


In [32]:
a = tf.constant([10, 20, 30])
b = tf.constant([1, 2,3])

In [25]:
# Addition of tensors
c = tf.add(a, b)
print(c)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [26]:
print(a+b)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [27]:
#Subtraction of tensors
d = tf.subtract(a, b)
print(d)

tf.Tensor([ 9 18 27], shape=(3,), dtype=int32)


In [28]:
print(a-b)

tf.Tensor([ 9 18 27], shape=(3,), dtype=int32)


In [33]:
#Element-wise multiplication
e=tf.multiply(a,b)
print(e)

tf.Tensor([10 40 90], shape=(3,), dtype=int32)


In [34]:
print(a * b)

tf.Tensor([10 40 90], shape=(3,), dtype=int32)


In [35]:
# Division of tensors
f = tf.divide(a, b)
print(f)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


In [36]:
print(a / b)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


In [38]:
# Floor division (integer division)
g = tf.math.floordiv(a, b)
print(g)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [39]:
#Power operation
p = tf.pow(b, 2)
print(p)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [40]:
#Matrix addition (same shape)
m1 = tf.constant([[1, 2],
                  [3,
4]])
m2 = tf.constant([[5, 6],
                  [7,
8]])
print(m1 + m2)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [44]:
t = tf.constant([[1, 2, 3],
                 [4,5,6]])

In [45]:
print(t.dtype, t.shape, t.ndim)

<dtype: 'int32'> (2, 3) 2


In [49]:
np_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

In [50]:
#Convert NumPy array to TensorFlow tensor
tensor = tf.convert_to_tensor(np_array)