In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


In [ ]:
corpus = [
# 📰 NEWS
"government announced new policy today",
"elections will be held next month",
"prime minister addressed the nation",
"new reforms are introduced in education",
"economy is growing steadily",
"inflation rates are increasing",
"new law was passed in parliament",
"citizens demand better infrastructure",
"weather department issued warning",
"news channels reported major events",

# 🏏 SPORTS
"india won the cricket match",
"team played very well today",
"virat kohli scored a century",
"football match was exciting",
"players trained hard for tournament",
"olympics bring global competition",
"fitness is important for athletes",
"teamwork leads to victory",
"coach guided the team well",
"sports improve physical health",

# 💻 TECHNOLOGY
"technology is evolving rapidly",
"artificial intelligence is the future",
"machine learning improves predictions",
"software development requires skills",
"cloud computing is widely used",
"cyber security is very important",
"data science is growing field",
"programming builds logical thinking",
"python is popular language",
"apps make life easier",

# 🏡 DAILY LIFE
"i wake up early every day",
"morning walk is refreshing",
"healthy food keeps us fit",
"i like to read books",
"music relaxes the mind",
"family time is important",
"friends make life enjoyable",
"sleep is essential for health",
"daily routine builds discipline",
"exercise improves fitness",

# 💼 BUSINESS
"companies focus on growth",
"market trends affect business",
"investment requires planning",
"startups are growing rapidly",
"entrepreneurs take risks",
"profits depend on strategy",
"digital marketing is important",
"customer satisfaction is key",
"sales increase revenue",
"business needs innovation",

# 🎓 EDUCATION
"students should study regularly",
"education builds strong foundation",
"teachers guide students",
"online learning is popular",
"exams test knowledge",
"practice improves performance",
"skills are more important than marks",
"learning new things is important",
"discipline helps in studies",
"focus improves concentration",

# 🌍 GENERAL KNOWLEDGE
"sun rises in the east",
"water is essential for life",
"earth revolves around the sun",
"plants produce oxygen",
"science explains natural phenomena",
"history teaches important lessons",
"geography studies the earth",
"environment needs protection",
"pollution harms nature",
"conservation saves resources",

# 🔥 MOTIVATION
"hard work leads to success",
"never give up easily",
"consistency is very important",
"confidence builds success",
"small steps create big change",
"focus on your goals",
"believe in yourself",
"success requires patience",
"failure teaches lessons",
"effort brings results",

# 🧠 AI / ML (for your model relevance)
"deep learning is powerful",
"neural networks learn patterns",
"lstm works on sequences",
"tokenization converts text",
"padding ensures equal length",
"embedding represents words",
"models improve with data",
"training increases accuracy",
"testing evaluates performance",
"prediction depends on input"
]

In [ ]:
print("Number of sentences:", len(corpus))
print("\nSample corpus:")
for line in corpus:
    print("-", line)


Number of sentences: 90

Sample corpus:
- government announced new policy today
- elections will be held next month
- prime minister addressed the nation
- new reforms are introduced in education
- economy is growing steadily
- inflation rates are increasing
- new law was passed in parliament
- citizens demand better infrastructure
- weather department issued warning
- news channels reported major events
- india won the cricket match
- team played very well today
- virat kohli scored a century
- football match was exciting
- players trained hard for tournament
- olympics bring global competition
- fitness is important for athletes
- teamwork leads to victory
- coach guided the team well
- sports improve physical health
- technology is evolving rapidly
- artificial intelligence is the future
- machine learning improves predictions
- software development requires skills
- cloud computing is widely used
- cyber security is very important
- data science is growing field
- programming build

In [ ]:

tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)

word_index = tokenizer.word_index
total_words = len(word_index) + 1

print("Vocabulary size:", total_words)
print("\nWord index:")
print(word_index)


Vocabulary size: 270

Word index:
{'is': 1, 'the': 2, 'important': 3, 'in': 4, 'on': 5, 'new': 6, 'are': 7, 'for': 8, 'learning': 9, 'improves': 10, 'builds': 11, 'growing': 12, 'very': 13, 'to': 14, 'requires': 15, 'life': 16, 'focus': 17, 'success': 18, 'today': 19, 'education': 20, 'was': 21, 'match': 22, 'team': 23, 'well': 24, 'hard': 25, 'fitness': 26, 'leads': 27, 'improve': 28, 'health': 29, 'rapidly': 30, 'skills': 31, 'data': 32, 'science': 33, 'popular': 34, 'make': 35, 'i': 36, 'up': 37, 'essential': 38, 'discipline': 39, 'business': 40, 'needs': 41, 'students': 42, 'performance': 43, 'studies': 44, 'sun': 45, 'earth': 46, 'teaches': 47, 'lessons': 48, 'government': 49, 'announced': 50, 'policy': 51, 'elections': 52, 'will': 53, 'be': 54, 'held': 55, 'next': 56, 'month': 57, 'prime': 58, 'minister': 59, 'addressed': 60, 'nation': 61, 'reforms': 62, 'introduced': 63, 'economy': 64, 'steadily': 65, 'inflation': 66, 'rates': 67, 'increasing': 68, 'law': 69, 'passed': 70, 'parl

In [ ]:

input_sequences = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

print("Total training sequences:", len(input_sequences))
print("\nSome sequences before padding:")
for seq in input_sequences[:10]:
    print(seq)


Total training sequences: 280

Some sequences before padding:
[49, 50]
[49, 50, 6]
[49, 50, 6, 51]
[49, 50, 6, 51, 19]
[52, 53]
[52, 53, 54]
[52, 53, 54, 55]
[52, 53, 54, 55, 56]
[52, 53, 54, 55, 56, 57]
[58, 59]


In [ ]:

max_seq_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_seq_len, padding='pre')

print("Maximum sequence length:", max_seq_len)
print("\nPadded sequences:")
print(input_sequences[:10])


Maximum sequence length: 6

Padded sequences:
[[ 0  0  0  0 49 50]
 [ 0  0  0 49 50  6]
 [ 0  0 49 50  6 51]
 [ 0 49 50  6 51 19]
 [ 0  0  0  0 52 53]
 [ 0  0  0 52 53 54]
 [ 0  0 52 53 54 55]
 [ 0 52 53 54 55 56]
 [52 53 54 55 56 57]
 [ 0  0  0  0 58 59]]


In [ ]:
# Step 1: Convert to numpy
input_sequences = np.array(input_sequences)

# Step 2: Split
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

# Step 3: One-hot encode
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# Step 4: Check shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (280, 5)
Shape of y: (280, 270)


In [ ]:

model = Sequential([
    Embedding(input_dim=total_words, output_dim=10, input_length=max_seq_len - 1),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

history = model.fit(X, y, epochs=180, verbose=1)


Epoch 1/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7357 - loss: 1.4217 
Epoch 2/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7464 - loss: 1.4095 
Epoch 3/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7393 - loss: 1.3984
Epoch 4/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7536 - loss: 1.3864 
Epoch 5/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 1.3737 
Epoch 6/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7536 - loss: 1.3580 
Epoch 7/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7643 - loss: 1.3479 
Epoch 8/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7679 - loss: 1.3334 
Epoch 9/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7643 - loss: 1.3247
Epoch 10/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7679 - loss: 1.3100 
Epoch 11/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7679 - loss: 1.3001 
Epoch 12/180
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7714 - loss

In [ ]:

def generate_text(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len - 1, padding='pre')

        predicted_probs = model.predict(token_list, verbose=0)
        predicted_index = np.argmax(predicted_probs, axis=-1)[0]

        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break

        seed_text += " " + output_word
    return seed_text


In [ ]:

print(generate_text("deep learning", 2))
print(generate_text("machine learning", 2))
print(generate_text("python is", 2))


deep learning is powerful
machine learning is popular
python is essential for
